apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- pluginConfig:
  plugins:
    multiPoint:
      disabled:
      - name: NodeUnschedulable
        weight: 1
  schedulerName: custom-scheduler