apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: sample-scheduler
    plugins:
      multiPoint:
        enabled:
        - name: 'Foobar'
          weight: 0